version: '3.7'

services:
  cloud-server:
    image: taxi-exp:0.0.1
    environment:
      NODE_TYPE: CLOUD_NODE

  taxi:
    image: taxi-exp:0.0.1
    environment:
      NODE_TYPE: IOT_NODE
    volumes:
      - /home/ubuntu/data:/data
  edge-node-bronx:
    image: taxi-exp:0.0.1
    environment:
      NODE_TYPE: EDGE_NODE
      REGION: bronx

  edge-node-brooklyn:
    image: taxi-exp:0.0.1
    environment:
      NODE_TYPE: EDGE_NODE
      REGION: brooklyn

  edge-node-manhattan:
    image: taxi-exp:0.0.1
    environment:
      NODE_TYPE: EDGE_NODE
      REGION: manhattan

  edge-node-queens:
    image: taxi-exp:0.0.1
    environment:
      NODE_TYPE: EDGE_NODE
      REGION: queens

  edge-node-satenisland:
    image: taxi-exp:0.0.1
    environment:
      NODE_TYPE: EDGE_NODE
      REGION: satenisland

x-fogify:
  nodes:
    - name: node-sm
      processor:
        cores: 1
        frequency: 2000
      memory: 1gb
    - name: node-lg
      processor:
        cores: 1
        frequency: 2000
      memory: 1gb

  networks:
    - name: internet
      uplink:
        bandwidth: 10Mbps
        latency:
          delay: 15ms
        drop: 0.0001
      downlink:
        bandwidth: 10Mbps
        latency:
          delay: 15ms
        drop: 0.0001
      links:
        - from_node: edge-node-bronx
          to_node: cloud-server
          properties: 2000ms
        - from_node: edge-node-bronx
          to_node: edge-node-bronx
          properties: 100ms
    - name: region_bronx
      uplink:
        bandwidth: 100Mbps
        latency:
          delay: 5ms
        drop: 0.0001
      downlink:
        bandwidth: 100Mbps
        latency:
          delay: 5ms
        drop: 0.0001
    - name: region_brooklyn
      uplink:
        bandwidth: 100Mbps
        latency:
          delay: 5ms
        drop: 0.0001
      downlink:
        bandwidth: 100Mbps
        latency:
          delay: 5ms
        drop: 0.0001
    - name: region_manhattan
      uplink:
        bandwidth: 100Mbps
        latency:
          delay: 5ms
        drop: 0.0001
      downlink:
        bandwidth: 100Mbps
        latency:
          delay: 5ms
        drop: 0.0001
    - name: region_queens
      uplink:
        bandwidth: 100Mbps
        latency:
          delay: 5ms
        drop: 0.0001
      downlink:
        bandwidth: 100Mbps
        latency:
          delay: 5ms
        drop: 0.0001
    - name: region_satenisland
      uplink:
        bandwidth: 100Mbps
        latency:
          delay: 5ms
        drop: 0.0001
      downlink:
        bandwidth: 100Mbps
        latency:
          delay: 5ms
        drop: 0.0001

  deployments:
    - name: general
      topology:
        - node: node-sm
          service: cloud-server
          label: cloud-server
          evaluation_metrics: all
          replicas: 1
          networks:
            - name: internet
              uplink:
                bandwidth: 10Mbps
                latency:
                  delay: 150ms
                drop: 0.0001
              downlink:
                bandwidth: 10Mbps
                latency:
                  delay: 150ms
                drop: 0.0001

        - node: node-sm
          service: edge-node-bronx
          evaluation_metrics: all
          label: edge-node-bronx
          replicas: 1
          networks:
            - internet
            - region_bronx
        - node: IoT
          service: taxi
          evaluation_metrics: all
          label: taxi-bronx
          replicas: 2
          networks:
            - internet
            - region_bronx

        - node: raspberry-pi-3b
          service: edge-node-brooklyn
          label: edge-node-brooklyn
          evaluation_metrics: all
          replicas: 1
          networks:
            - internet
            - region_brooklyn
        - node: IoT
          service: taxi
          label: taxi-brooklyn
          evaluation_metrics: all
          replicas: 2
          networks:
            - internet
            - region_brooklyn

        - node: raspberry-pi-3b
          service: edge-node-manhattan
          label: edge-node-manhattan
          evaluation_metrics: all
          replicas: 1
          networks:
            - internet
            - region_manhattan
        - node: IoT
          service: taxi
          label: taxi-manhattan
          evaluation_metrics: all
          replicas: 2
          networks:
            - internet
            - region_manhattan

        - node: raspberry-pi-3b
          service: edge-node-queens
          label: edge-node-queens
          evaluation_metrics: all
          replicas: 1
          networks:
            - internet
            - region_queens
        - node: IoT
          service: taxi
          label: taxi-queens
          evaluation_metrics: all
          replicas: 2
          networks:
            - internet
            - region_queens

        - node: raspberry-pi-3b
          service: edge-node-satenisland
          label: edge-node-satenisland
          evaluation_metrics: all
          replicas: 1
          networks:
            - internet
            - region_satenisland
        - node: IoT
          service: taxi
          label: taxi-satenisland
          evaluation_metrics: all
          replicas: 2
          networks:
            - internet
            - region_satenisland

        - node: IoT
          service: taxi
          label: taxi-suburbs
          evaluation_metrics: all
          replicas: 1
          networks:
            - internet